### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by ZZKdev** [easyworld/PlayJumpJumpWithMouse#11]
Error: Unable to access jarfile C:\Users\ZZK\Desktop\PlayJumpJumpWithMouse-master\src\main\java\com\company\playJumpJumpWithMouse.jar

**Comment by easyworld** [comment]
运行的命令可以看下吗？

**Comment by ZZKdev** [comment]
java -jar C:\Users\ZZK\Desktop\PlayJumpJumpWithMouse-master\src\main\java\com\company\playJumpJumpWithMouse -a C:\Users\ZZK\Desktop\platform-tools\adb.exe

有点长。

**Comment by ZZKdev** [comment]
发错了。是这个
java -jar C:\Users\ZZK\Desktop\playJumpJumpWithMouse.jar -a C:\Users\ZZK\Desktop\platform-tools

**Comment by easyworld** [comment]
```
java -jar C:\Users\ZZK\Desktop\playJumpJumpWithMouse.jar -a "C:\Users\ZZK\Desktop\platform-tools\adb.exe"
```
试试这样

**Comment by ZZKdev** [comment]
还是不行。

**Comment by chxv** [comment]
这个问题我也遇到了，请问下载后是直接解压就行吗？或者需要自行编译？

**Comment by easyworld** [comment]
@ZZKdev @cshsonice 你们下载的是[这个吗](https://github.com/easyworld/PlayJumpJumpWithMouse/releases/download/v0.0.1/playJumpJumpWithMouse.jar)

**Comment by chxv** [comment]
网址打不开？

**Comment by ZZKdev** [comment]
这次好了可是出现的那个是白屏

**Comment by easyworld** [comment]
@ZZKdev 命令行运行adb看下，感觉像是adb端口被占用了

**Comment by ZZKdev** [comment]
命令行可以运行，运行完是这样的
C:\Users\ZZK>C:\Users\ZZK\Desktop\platform-tools\adb.exe
Android Debug Bridge version 1.0.39
Version 0.0.1-4500957
Installed as C:\Users\ZZK\Desktop\platform-tools\adb.exe

global options:
 -a         listen on all network interfaces, not just localhost
 -d         use USB device (error if multiple devices connected)
 -e         use TCP/IP device (error if multiple TCP/IP devices available)
 -s SERIAL  use device with given serial (overrides $ANDROID_SERIAL)
 -t ID      use device with given transport id
 -H         name of adb server host [default=localhost]
 -P         port of adb server [default=5037]

**Comment by ZZKdev** [comment]
这样的话就白屏，但是我点击白屏它会打印距离那些东西

C:\Users\ZZK>java -jar C:\Users\ZZK\Desktop\playJumpJumpWithMouse.jar -aC:\Users\ZZK\Desktop\platform-tools\adb.exe
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at com.company.playJumpJumpWithMouse.BackgroundImage4Panel$1.paintComponent(BackgroundImage4Panel.java:148)
        at javax.swing.JComponent.paint(Unknown Source)
        at javax.swing.JComponent.paintChildren(Unknown Source)
        at javax.swing.JComponent.paint(Unknown Source)
        at javax.swing.JComponent.paintChildren(Unknown Source)
        at javax.swing.JComponent.paint(Unknown Source)
        at javax.swing.JLayeredPane.paint(Unknown Source)
        at javax.swing.JComponent.paintChildren(Unknown Source)
        at javax.swing.JComponent.paintToOffscreen(Unknown Source)
        at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(Unknown Source)
        at javax.swing.RepaintManager$PaintManager.paint(Unknown Source)
        at javax.swing.RepaintManager.paint(Unknown Source)
        at javax.swing.JComponent.paint(Unknown Source)
        at java.awt.GraphicsCallback$PaintCallback.run(Unknown Source)
        at sun.awt.SunGraphicsCallback.runOneComponent(Unknown Source)
        at sun.awt.SunGraphicsCallback.runComponents(Unknown Source)
        at java.awt.Container.paint(Unknown Source)
        at java.awt.Window.paint(Unknown Source)
        at javax.swing.RepaintManager$4.run(Unknown Source)
        at javax.swing.RepaintManager$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
        at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
        at javax.swing.RepaintManager.prePaintDirtyRegions(Unknown Source)
        at javax.swing.RepaintManager.access$1200(Unknown Source)
        at javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by ZZKdev** [comment]
已经可以了。
原因是没有开USB调试模式

**Comment by ylrh3** [comment]
我也是，运行这个命令后，就出现白屏！java -jar C:\playJumpJumpWithMouse.jar -a "C:\platform-tools\adb.exe"

**Comment by JKAK47** [comment]
需要自己MAVEN 编译吗？
生成的是playJumpJumpWithMouse-0.0.1-SNAPSHOT.jar 怎么是playJumpJumpWithMouse.jar呢

**Comment by Lixing1993** [comment]
手机需要root吗？

**Comment by easyworld** [comment]
@ylrh3 运行adb shell看下有没有连上手机
@JKAK47 重命名
@Lixing1993 不需要
