### ISSUE TITLE
Honor 8安卓手机 运行后界面出不来，一直都是空白

### ISSUE THREAD

**Issue by JKAK47** [easyworld/PlayJumpJumpWithMouse#13]

**Comment by JKAK47** [comment]
我是直接下载源码，我改了
public static final String ADB_PATH = "C:\\Users\\PengRong\\Desktop\\adb\\platform-tools\\adb.exe";
	public static final String SCREENSHOT_LOCATION = "C:\\Users\\PengRong\\Desktop\\adb\\img\\s.png";
这两个常量是我下载下adb 在我本机的地址。然后运行的命令是
在工程编译后生成的target目录下执行的。
执行命令如下
`java -jar playJumpJumpWithMouse-0.0.1-SNAPSHOT.jar -a  "C:\Users\PengRong\Desktop\adb\platform-tools\adb.exe"`

**Comment by JKAK47** [comment]
cmd 报错异常信息：
```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at com.company.playJumpJumpWithMouse.BackgroundImage4Panel$1.paintComponent(BackgroundImage4Panel.java:149)
        at javax.swing.JComponent.paint(Unknown Source)
        at javax.swing.JComponent.paintChildren(Unknown Source)
        at javax.swing.JComponent.paint(Unknown Source)
        at javax.swing.JComponent.paintChildren(Unknown Source)
        at javax.swing.JComponent.paint(Unknown Source)
        at javax.swing.JLayeredPane.paint(Unknown Source)
        at javax.swing.JComponent.paintChildren(Unknown Source)
        at javax.swing.JComponent.paintToOffscreen(Unknown Source)
        at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(Unknown Source)
        at javax.swing.RepaintManager$PaintManager.paint(Unknown Source)
        at javax.swing.RepaintManager.paint(Unknown Source)
        at javax.swing.JComponent.paint(Unknown Source)
        at java.awt.GraphicsCallback$PaintCallback.run(Unknown Source)
        at sun.awt.SunGraphicsCallback.runOneComponent(Unknown Source)
        at sun.awt.SunGraphicsCallback.runComponents(Unknown Source)
        at java.awt.Container.paint(Unknown Source)
        at java.awt.Window.paint(Unknown Source)
        at javax.swing.RepaintManager$4.run(Unknown Source)
        at javax.swing.RepaintManager$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
        at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
        at javax.swing.RepaintManager.prePaintDirtyRegions(Unknown Source)
        at javax.swing.RepaintManager.access$1200(Unknown Source)
        at javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by JKAK47** [comment]
![](http://one17356s.bkt.clouddn.com/17-12-30/2721320.jpg)

**Comment by qq347447474** [comment]
同

**Comment by easyworld** [comment]
电脑终端运行下adb，看看连上手机了吗
