### ISSUE TITLE
生成的图片打不开，报错如下

### ISSUE THREAD

**Issue by BytesZero** [easyworld/PlayJumpJumpWithMouse#23]
![s](https://user-images.githubusercontent.com/8764899/34460404-9cc24e7e-ee47-11e7-9e8e-5946a7e0dc58.png)

图片加载失败，是95k 
<img width="415" alt="default" src="https://user-images.githubusercontent.com/8764899/34460411-f3e49acc-ee47-11e7-8cc7-39c750ffe4db.png">

```java
bogon:~ zsl$ java -jar /Users/zsl/Downloads/playJumpJumpWithMouse-0.0.2.jar -a /Users/zsl/android/sdk/android-sdk-macosx/platform-tools/adb -m 2
Exception in thread "Thread-0" java.lang.NullPointerException
	at com.company.playJumpJumpWithMouse.StartCenterFinder.findStartCenter(StartCenterFinder.java:95)
	at com.company.playJumpJumpWithMouse.BackgroundImage4Panel$3.run(BackgroundImage4Panel.java:252)
```

**Comment by BytesZero** [comment]
建议建个群讨论，这样速度太慢啦，github
